<?php

/**
 * AdressApi
 * PHP version 5
 *
 * @category Class
 * @package  MerciFacteurApi\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Merci facteur API
 *
 * Merci facteur PRO vous permet d'envoyer des courriers depuis votre applicatif via son API.     Types de courriers disponibles :   - Lettre de une ou plusieurs pages.  - Carte postale avec ou sans enveloppe  - Carte pliée  - Carte géante  - Carte non pliée  - Photos sur papier brillant    Modes d'envois disponibles :   - Envoi normal (lettre verte)  - Lettre suivie  - Recommandé avec avis de réception      Au sujet des webhooks : [`https://github.com/MerciFacteur/Merci-facteur-API/blob/master/README.md#webhooks`](https://github.com/MerciFacteur/Merci-facteur-API/blob/master/README.md#webhooks)     Librairie PHP et exemples d'intégration : [`https://github.com/MerciFacteur/Merci-facteur-API`](https://github.com/MerciFacteur/Merci-facteur-API)    Infos générales sur l'API : [`https://github.com/MerciFacteur/Merci-facteur-API/blob/master/README.md`](https://github.com/MerciFacteur/Merci-facteur-API/blob/master/README.md)    Plus d'informations sur [`https://www.merci-facteur.com/pro`](https://www.merci-facteur.com/pro)    N'hésitez pas à nous contacter via [`https://www.merci-facteur.com/pro/contact.php`](https://www.merci-facteur.com/pro/contact.php)
 *
 * OpenAPI spec version: 1.2.7
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.51
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace MerciFacteurApi\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use MerciFacteurApi\Client\ApiException;
use MerciFacteurApi\Client\Configuration;
use MerciFacteurApi\Client\HeaderSelector;
use MerciFacteurApi\Client\ObjectSerializer;

/**
 * AdressApi Class Doc Comment
 *
 * @category Class
 * @package  MerciFacteurApi\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AdressApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation deleteAdress
     *
     * Supprimer une adresse
     *
     * @param  string $ww_service_id Votre service Id (required)
     * @param  string $ww_access_token Un access token valide (required)
     * @param  int $id_adress ID de l&#x27;adresse à supprimer (required)
     *
     * @throws \MerciFacteurApi\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \MerciFacteurApi\Client\Model\InlineResponse2002
     */
    public function deleteAdress($ww_service_id, $ww_access_token, $id_adress)
    {
        list($response) = $this->deleteAdressWithHttpInfo($ww_service_id, $ww_access_token, $id_adress);
        return $response;
    }

    /**
     * Operation deleteAdressWithHttpInfo
     *
     * Supprimer une adresse
     *
     * @param  string $ww_service_id Votre service Id (required)
     * @param  string $ww_access_token Un access token valide (required)
     * @param  int $id_adress ID de l&#x27;adresse à supprimer (required)
     *
     * @throws \MerciFacteurApi\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \MerciFacteurApi\Client\Model\InlineResponse2002, HTTP status code, HTTP response headers (array of strings)
     */
    public function deleteAdressWithHttpInfo($ww_service_id, $ww_access_token, $id_adress)
    {
        $returnType = '\MerciFacteurApi\Client\Model\InlineResponse2002';
        $request = $this->deleteAdressRequest($ww_service_id, $ww_access_token, $id_adress);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string', 'integer', 'bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\MerciFacteurApi\Client\Model\InlineResponse2002',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\MerciFacteurApi\Client\Model\InlineResponse400',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\MerciFacteurApi\Client\Model\InlineResponse400',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation deleteAdressAsync
     *
     * Supprimer une adresse
     *
     * @param  string $ww_service_id Votre service Id (required)
     * @param  string $ww_access_token Un access token valide (required)
     * @param  int $id_adress ID de l&#x27;adresse à supprimer (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteAdressAsync($ww_service_id, $ww_access_token, $id_adress)
    {
        return $this->deleteAdressAsyncWithHttpInfo($ww_service_id, $ww_access_token, $id_adress)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation deleteAdressAsyncWithHttpInfo
     *
     * Supprimer une adresse
     *
     * @param  string $ww_service_id Votre service Id (required)
     * @param  string $ww_access_token Un access token valide (required)
     * @param  int $id_adress ID de l&#x27;adresse à supprimer (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteAdressAsyncWithHttpInfo($ww_service_id, $ww_access_token, $id_adress)
    {
        $returnType = '\MerciFacteurApi\Client\Model\InlineResponse2002';
        $request = $this->deleteAdressRequest($ww_service_id, $ww_access_token, $id_adress);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'deleteAdress'
     *
     * @param  string $ww_service_id Votre service Id (required)
     * @param  string $ww_access_token Un access token valide (required)
     * @param  int $id_adress ID de l&#x27;adresse à supprimer (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function deleteAdressRequest($ww_service_id, $ww_access_token, $id_adress)
    {
        // verify the required parameter 'ww_service_id' is set
        if ($ww_service_id === null || (is_array($ww_service_id) && count($ww_service_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $ww_service_id when calling deleteAdress'
            );
        }
        // verify the required parameter 'ww_access_token' is set
        if ($ww_access_token === null || (is_array($ww_access_token) && count($ww_access_token) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $ww_access_token when calling deleteAdress'
            );
        }
        // verify the required parameter 'id_adress' is set
        if ($id_adress === null || (is_array($id_adress) && count($id_adress) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id_adress when calling deleteAdress'
            );
        }

        $resourcePath = '/deleteAdress';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($id_adress !== null) {
            $queryParams['idAdress'] = ObjectSerializer::toQueryValue($id_adress, null);
        }
        // header params
        if ($ww_service_id !== null) {
            $headerParams['ww-service-id'] = ObjectSerializer::toHeaderValue($ww_service_id);
        }
        // header params
        if ($ww_access_token !== null) {
            $headerParams['ww-access-token'] = ObjectSerializer::toHeaderValue($ww_access_token);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);
            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'DELETE',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getAdressInfos
     *
     * Obtenir les infos complètes d'une ou plusieurs adresse(s) à partir de leurs adresse Id (destinataire ou expéditeur).
     *
     * @param  string $ww_service_id Votre service Id (required)
     * @param  string $ww_access_token Un access token valide (required)
     * @param  int[] $id_adress Les adresse Id des adresses dont vous souhaitez extraire les informations (maximum 50 adresses à la fois). (required)
     *
     * @throws \MerciFacteurApi\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \MerciFacteurApi\Client\Model\InlineResponse2007
     */
    public function getAdressInfos($ww_service_id, $ww_access_token, $id_adress)
    {
        list($response) = $this->getAdressInfosWithHttpInfo($ww_service_id, $ww_access_token, $id_adress);
        return $response;
    }

    /**
     * Operation getAdressInfosWithHttpInfo
     *
     * Obtenir les infos complètes d'une ou plusieurs adresse(s) à partir de leurs adresse Id (destinataire ou expéditeur).
     *
     * @param  string $ww_service_id Votre service Id (required)
     * @param  string $ww_access_token Un access token valide (required)
     * @param  int[] $id_adress Les adresse Id des adresses dont vous souhaitez extraire les informations (maximum 50 adresses à la fois). (required)
     *
     * @throws \MerciFacteurApi\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \MerciFacteurApi\Client\Model\InlineResponse2007, HTTP status code, HTTP response headers (array of strings)
     */
    public function getAdressInfosWithHttpInfo($ww_service_id, $ww_access_token, $id_adress)
    {
        $returnType = '\MerciFacteurApi\Client\Model\InlineResponse2007';
        $request = $this->getAdressInfosRequest($ww_service_id, $ww_access_token, $id_adress);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string', 'integer', 'bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                json_decode($content, true),
                $response->getStatusCode(),
                $response->getHeaders()
            ];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\MerciFacteurApi\Client\Model\InlineResponse2007',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\MerciFacteurApi\Client\Model\InlineResponse400',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\MerciFacteurApi\Client\Model\InlineResponse400',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getAdressInfosAsync
     *
     * Obtenir les infos complètes d'une ou plusieurs adresse(s) à partir de leurs adresse Id (destinataire ou expéditeur).
     *
     * @param  string $ww_service_id Votre service Id (required)
     * @param  string $ww_access_token Un access token valide (required)
     * @param  int[] $id_adress Les adresse Id des adresses dont vous souhaitez extraire les informations (maximum 50 adresses à la fois). (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getAdressInfosAsync($ww_service_id, $ww_access_token, $id_adress)
    {
        return $this->getAdressInfosAsyncWithHttpInfo($ww_service_id, $ww_access_token, $id_adress)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getAdressInfosAsyncWithHttpInfo
     *
     * Obtenir les infos complètes d'une ou plusieurs adresse(s) à partir de leurs adresse Id (destinataire ou expéditeur).
     *
     * @param  string $ww_service_id Votre service Id (required)
     * @param  string $ww_access_token Un access token valide (required)
     * @param  int[] $id_adress Les adresse Id des adresses dont vous souhaitez extraire les informations (maximum 50 adresses à la fois). (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getAdressInfosAsyncWithHttpInfo($ww_service_id, $ww_access_token, $id_adress)
    {
        $returnType = '\MerciFacteurApi\Client\Model\InlineResponse2007';
        $request = $this->getAdressInfosRequest($ww_service_id, $ww_access_token, $id_adress);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getAdressInfos'
     *
     * @param  string $ww_service_id Votre service Id (required)
     * @param  string $ww_access_token Un access token valide (required)
     * @param  int[] $id_adress Les adresse Id des adresses dont vous souhaitez extraire les informations (maximum 50 adresses à la fois). (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getAdressInfosRequest($ww_service_id, $ww_access_token, $id_adress)
    {
        // verify the required parameter 'ww_service_id' is set
        if ($ww_service_id === null || (is_array($ww_service_id) && count($ww_service_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $ww_service_id when calling getAdressInfos'
            );
        }
        // verify the required parameter 'ww_access_token' is set
        if ($ww_access_token === null || (is_array($ww_access_token) && count($ww_access_token) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $ww_access_token when calling getAdressInfos'
            );
        }
        // verify the required parameter 'id_adress' is set
        if ($id_adress === null || (is_array($id_adress) && count($id_adress) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id_adress when calling getAdressInfos'
            );
        }

        $resourcePath = '/getAdressInfos';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if (is_array($id_adress)) {
            $id_adress = ObjectSerializer::serializeCollection($id_adress, 'multi', true);
        }
        if ($id_adress !== null) {
            $queryParams['idAdress[]'] = ObjectSerializer::toQueryValue($id_adress, null);
        }
        // header params
        if ($ww_service_id !== null) {
            $headerParams['ww-service-id'] = ObjectSerializer::toHeaderValue($ww_service_id);
        }
        // header params
        if ($ww_access_token !== null) {
            $headerParams['ww-access-token'] = ObjectSerializer::toHeaderValue($ww_access_token);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);
            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getCountry
     *
     * Obtenir la liste des pays valides
     *
     * @param  string $ww_service_id Votre service Id (required)
     * @param  string $ww_access_token Un access token valide (required)
     * @param  string[] $zone Les zones à extraire : fr,z1,z2,om1,om2 (required)
     *
     * @throws \MerciFacteurApi\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \MerciFacteurApi\Client\Model\InlineResponse2004
     */
    public function getCountry($ww_service_id, $ww_access_token, $zone)
    {
        list($response) = $this->getCountryWithHttpInfo($ww_service_id, $ww_access_token, $zone);
        return $response;
    }

    /**
     * Operation getCountryWithHttpInfo
     *
     * Obtenir la liste des pays valides
     *
     * @param  string $ww_service_id Votre service Id (required)
     * @param  string $ww_access_token Un access token valide (required)
     * @param  string[] $zone Les zones à extraire : fr,z1,z2,om1,om2 (required)
     *
     * @throws \MerciFacteurApi\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \MerciFacteurApi\Client\Model\InlineResponse2004, HTTP status code, HTTP response headers (array of strings)
     */
    public function getCountryWithHttpInfo($ww_service_id, $ww_access_token, $zone)
    {
        $returnType = '\MerciFacteurApi\Client\Model\InlineResponse2004';
        $request = $this->getCountryRequest($ww_service_id, $ww_access_token, $zone);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string', 'integer', 'bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\MerciFacteurApi\Client\Model\InlineResponse2004',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\MerciFacteurApi\Client\Model\InlineResponse400',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\MerciFacteurApi\Client\Model\InlineResponse400',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getCountryAsync
     *
     * Obtenir la liste des pays valides
     *
     * @param  string $ww_service_id Votre service Id (required)
     * @param  string $ww_access_token Un access token valide (required)
     * @param  string[] $zone Les zones à extraire : fr,z1,z2,om1,om2 (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getCountryAsync($ww_service_id, $ww_access_token, $zone)
    {
        return $this->getCountryAsyncWithHttpInfo($ww_service_id, $ww_access_token, $zone)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getCountryAsyncWithHttpInfo
     *
     * Obtenir la liste des pays valides
     *
     * @param  string $ww_service_id Votre service Id (required)
     * @param  string $ww_access_token Un access token valide (required)
     * @param  string[] $zone Les zones à extraire : fr,z1,z2,om1,om2 (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getCountryAsyncWithHttpInfo($ww_service_id, $ww_access_token, $zone)
    {
        $returnType = '\MerciFacteurApi\Client\Model\InlineResponse2004';
        $request = $this->getCountryRequest($ww_service_id, $ww_access_token, $zone);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getCountry'
     *
     * @param  string $ww_service_id Votre service Id (required)
     * @param  string $ww_access_token Un access token valide (required)
     * @param  string[] $zone Les zones à extraire : fr,z1,z2,om1,om2 (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getCountryRequest($ww_service_id, $ww_access_token, $zone)
    {
        // verify the required parameter 'ww_service_id' is set
        if ($ww_service_id === null || (is_array($ww_service_id) && count($ww_service_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $ww_service_id when calling getCountry'
            );
        }
        // verify the required parameter 'ww_access_token' is set
        if ($ww_access_token === null || (is_array($ww_access_token) && count($ww_access_token) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $ww_access_token when calling getCountry'
            );
        }
        // verify the required parameter 'zone' is set
        if ($zone === null || (is_array($zone) && count($zone) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $zone when calling getCountry'
            );
        }

        $resourcePath = '/getCountry';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if (is_array($zone)) {
            $zone = ObjectSerializer::serializeCollection($zone, 'multi', true);
        }
        if ($zone !== null) {
            $queryParams['zone[]'] = ObjectSerializer::toQueryValue($zone, null);
        }
        // header params
        if ($ww_service_id !== null) {
            $headerParams['ww-service-id'] = ObjectSerializer::toHeaderValue($ww_service_id);
        }
        // header params
        if ($ww_access_token !== null) {
            $headerParams['ww-access-token'] = ObjectSerializer::toHeaderValue($ww_access_token);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);
            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation listAdress
     *
     * Lister les adresses du carnet d'adresses d'un utilisateur. Limité à 500 adresses. Pour plus de précision dans la recherche utilisez le paramètre \"search\".
     *
     * @param  string $ww_service_id Votre service Id (required)
     * @param  string $ww_access_token Un access token valide (required)
     * @param  int $id_user User Id de l&#x27;utilisateur propriétaire de cette adresse. (required)
     * @param  string $type Type d&#x27;adresse : Expéditeur (exp) ou destinataire (dest) (required)
     * @param  string $search Recherche d&#x27;une adresse précise (de la forme {\&quot;nom\&quot;:\&quot;\&quot;,\&quot;societe\&quot;:\&quot;\&quot;,\&quot;cp\&quot;:\&quot;\&quot;,\&quot;ville\&quot;:\&quot;\&quot;}). (optional)
     *
     * @throws \MerciFacteurApi\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \MerciFacteurApi\Client\Model\InlineResponse2006
     */
    public function listAdress($ww_service_id, $ww_access_token, $id_user, $type, $search = null)
    {
        list($response) = $this->listAdressWithHttpInfo($ww_service_id, $ww_access_token, $id_user, $type, $search);
        return $response;
    }

    /**
     * Operation listAdressWithHttpInfo
     *
     * Lister les adresses du carnet d'adresses d'un utilisateur. Limité à 500 adresses. Pour plus de précision dans la recherche utilisez le paramètre \"search\".
     *
     * @param  string $ww_service_id Votre service Id (required)
     * @param  string $ww_access_token Un access token valide (required)
     * @param  int $id_user User Id de l&#x27;utilisateur propriétaire de cette adresse. (required)
     * @param  string $type Type d&#x27;adresse : Expéditeur (exp) ou destinataire (dest) (required)
     * @param  string $search Recherche d&#x27;une adresse précise (de la forme {\&quot;nom\&quot;:\&quot;\&quot;,\&quot;societe\&quot;:\&quot;\&quot;,\&quot;cp\&quot;:\&quot;\&quot;,\&quot;ville\&quot;:\&quot;\&quot;}). (optional)
     *
     * @throws \MerciFacteurApi\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \MerciFacteurApi\Client\Model\InlineResponse2006, HTTP status code, HTTP response headers (array of strings)
     */
    public function listAdressWithHttpInfo($ww_service_id, $ww_access_token, $id_user, $type, $search = null)
    {
        $returnType = '\MerciFacteurApi\Client\Model\InlineResponse2006';
        $request = $this->listAdressRequest($ww_service_id, $ww_access_token, $id_user, $type, $search);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string', 'integer', 'bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\MerciFacteurApi\Client\Model\InlineResponse2006',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\MerciFacteurApi\Client\Model\InlineResponse400',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\MerciFacteurApi\Client\Model\InlineResponse400',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation listAdressAsync
     *
     * Lister les adresses du carnet d'adresses d'un utilisateur. Limité à 500 adresses. Pour plus de précision dans la recherche utilisez le paramètre \"search\".
     *
     * @param  string $ww_service_id Votre service Id (required)
     * @param  string $ww_access_token Un access token valide (required)
     * @param  int $id_user User Id de l&#x27;utilisateur propriétaire de cette adresse. (required)
     * @param  string $type Type d&#x27;adresse : Expéditeur (exp) ou destinataire (dest) (required)
     * @param  string $search Recherche d&#x27;une adresse précise (de la forme {\&quot;nom\&quot;:\&quot;\&quot;,\&quot;societe\&quot;:\&quot;\&quot;,\&quot;cp\&quot;:\&quot;\&quot;,\&quot;ville\&quot;:\&quot;\&quot;}). (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listAdressAsync($ww_service_id, $ww_access_token, $id_user, $type, $search = null)
    {
        return $this->listAdressAsyncWithHttpInfo($ww_service_id, $ww_access_token, $id_user, $type, $search)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation listAdressAsyncWithHttpInfo
     *
     * Lister les adresses du carnet d'adresses d'un utilisateur. Limité à 500 adresses. Pour plus de précision dans la recherche utilisez le paramètre \"search\".
     *
     * @param  string $ww_service_id Votre service Id (required)
     * @param  string $ww_access_token Un access token valide (required)
     * @param  int $id_user User Id de l&#x27;utilisateur propriétaire de cette adresse. (required)
     * @param  string $type Type d&#x27;adresse : Expéditeur (exp) ou destinataire (dest) (required)
     * @param  string $search Recherche d&#x27;une adresse précise (de la forme {\&quot;nom\&quot;:\&quot;\&quot;,\&quot;societe\&quot;:\&quot;\&quot;,\&quot;cp\&quot;:\&quot;\&quot;,\&quot;ville\&quot;:\&quot;\&quot;}). (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listAdressAsyncWithHttpInfo($ww_service_id, $ww_access_token, $id_user, $type, $search = null)
    {
        $returnType = '\MerciFacteurApi\Client\Model\InlineResponse2006';
        $request = $this->listAdressRequest($ww_service_id, $ww_access_token, $id_user, $type, $search);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'listAdress'
     *
     * @param  string $ww_service_id Votre service Id (required)
     * @param  string $ww_access_token Un access token valide (required)
     * @param  int $id_user User Id de l&#x27;utilisateur propriétaire de cette adresse. (required)
     * @param  string $type Type d&#x27;adresse : Expéditeur (exp) ou destinataire (dest) (required)
     * @param  string $search Recherche d&#x27;une adresse précise (de la forme {\&quot;nom\&quot;:\&quot;\&quot;,\&quot;societe\&quot;:\&quot;\&quot;,\&quot;cp\&quot;:\&quot;\&quot;,\&quot;ville\&quot;:\&quot;\&quot;}). (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function listAdressRequest($ww_service_id, $ww_access_token, $id_user, $type, $search = null)
    {
        // verify the required parameter 'ww_service_id' is set
        if ($ww_service_id === null || (is_array($ww_service_id) && count($ww_service_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $ww_service_id when calling listAdress'
            );
        }
        // verify the required parameter 'ww_access_token' is set
        if ($ww_access_token === null || (is_array($ww_access_token) && count($ww_access_token) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $ww_access_token when calling listAdress'
            );
        }
        // verify the required parameter 'id_user' is set
        if ($id_user === null || (is_array($id_user) && count($id_user) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id_user when calling listAdress'
            );
        }
        // verify the required parameter 'type' is set
        if ($type === null || (is_array($type) && count($type) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $type when calling listAdress'
            );
        }

        $resourcePath = '/listAdress';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($id_user !== null) {
            $queryParams['idUser'] = ObjectSerializer::toQueryValue($id_user, null);
        }
        // query params
        if ($type !== null) {
            $queryParams['type'] = ObjectSerializer::toQueryValue($type, null);
        }
        // query params
        if ($search !== null) {
            $queryParams['search'] = ObjectSerializer::toQueryValue($search, null);
        }
        // header params
        if ($ww_service_id !== null) {
            $headerParams['ww-service-id'] = ObjectSerializer::toHeaderValue($ww_service_id);
        }
        // header params
        if ($ww_access_token !== null) {
            $headerParams['ww-access-token'] = ObjectSerializer::toHeaderValue($ww_access_token);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);
            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation setNewAdress
     *
     * Créer une nouvelle adresse dans le carnet d'adresses (non obligatoire pour l'envoi d'un courrier)
     *
     * @param  string $ww_service_id Votre service Id (required)
     * @param  string $ww_access_token Un access token valide (required)
     * @param  int $id_user User Id de l&#x27;utilisateur propriétaire de cette adresse. (required)
     * @param  string $type Type d&#x27;adresse : Expéditeur (exp) ou destinataire (dest) (required)
     * @param  \MerciFacteurApi\Client\Model\AdressInfosAdress $adress adress (optional)
     *
     * @throws \MerciFacteurApi\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \MerciFacteurApi\Client\Model\InlineResponse2005
     */
    public function setNewAdress($ww_service_id, $ww_access_token, $id_user, $type, $adress = null)
    {
        list($response) = $this->setNewAdressWithHttpInfo($ww_service_id, $ww_access_token, $id_user, $type, $adress);
        return $response;
    }

    /**
     * Operation setNewAdressWithHttpInfo
     *
     * Créer une nouvelle adresse dans le carnet d'adresses (non obligatoire pour l'envoi d'un courrier)
     *
     * @param  string $ww_service_id Votre service Id (required)
     * @param  string $ww_access_token Un access token valide (required)
     * @param  int $id_user User Id de l&#x27;utilisateur propriétaire de cette adresse. (required)
     * @param  string $type Type d&#x27;adresse : Expéditeur (exp) ou destinataire (dest) (required)
     * @param  \MerciFacteurApi\Client\Model\AdressInfosAdress $adress (optional)
     *
     * @throws \MerciFacteurApi\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \MerciFacteurApi\Client\Model\InlineResponse2005, HTTP status code, HTTP response headers (array of strings)
     */
    public function setNewAdressWithHttpInfo($ww_service_id, $ww_access_token, $id_user, $type, $adress = null)
    {
        $returnType = '\MerciFacteurApi\Client\Model\InlineResponse2005';
        $request = $this->setNewAdressRequest($ww_service_id, $ww_access_token, $id_user, $type, $adress);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string', 'integer', 'bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\MerciFacteurApi\Client\Model\InlineResponse2005',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\MerciFacteurApi\Client\Model\InlineResponse400',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\MerciFacteurApi\Client\Model\InlineResponse400',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation setNewAdressAsync
     *
     * Créer une nouvelle adresse dans le carnet d'adresses (non obligatoire pour l'envoi d'un courrier)
     *
     * @param  string $ww_service_id Votre service Id (required)
     * @param  string $ww_access_token Un access token valide (required)
     * @param  int $id_user User Id de l&#x27;utilisateur propriétaire de cette adresse. (required)
     * @param  string $type Type d&#x27;adresse : Expéditeur (exp) ou destinataire (dest) (required)
     * @param  \MerciFacteurApi\Client\Model\AdressInfosAdress $adress (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function setNewAdressAsync($ww_service_id, $ww_access_token, $id_user, $type, $adress = null)
    {
        return $this->setNewAdressAsyncWithHttpInfo($ww_service_id, $ww_access_token, $id_user, $type, $adress)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation setNewAdressAsyncWithHttpInfo
     *
     * Créer une nouvelle adresse dans le carnet d'adresses (non obligatoire pour l'envoi d'un courrier)
     *
     * @param  string $ww_service_id Votre service Id (required)
     * @param  string $ww_access_token Un access token valide (required)
     * @param  int $id_user User Id de l&#x27;utilisateur propriétaire de cette adresse. (required)
     * @param  string $type Type d&#x27;adresse : Expéditeur (exp) ou destinataire (dest) (required)
     * @param  \MerciFacteurApi\Client\Model\AdressInfosAdress $adress (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function setNewAdressAsyncWithHttpInfo($ww_service_id, $ww_access_token, $id_user, $type, $adress = null)
    {
        $returnType = '\MerciFacteurApi\Client\Model\InlineResponse2005';
        $request = $this->setNewAdressRequest($ww_service_id, $ww_access_token, $id_user, $type, $adress);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'setNewAdress'
     *
     * @param  string $ww_service_id Votre service Id (required)
     * @param  string $ww_access_token Un access token valide (required)
     * @param  int $id_user User Id de l&#x27;utilisateur propriétaire de cette adresse. (required)
     * @param  string $type Type d&#x27;adresse : Expéditeur (exp) ou destinataire (dest) (required)
     * @param  \MerciFacteurApi\Client\Model\AdressInfosAdress $adress (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function setNewAdressRequest($ww_service_id, $ww_access_token, $id_user, $type, $adress = null)
    {
        // verify the required parameter 'ww_service_id' is set
        if ($ww_service_id === null || (is_array($ww_service_id) && count($ww_service_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $ww_service_id when calling setNewAdress'
            );
        }
        // verify the required parameter 'ww_access_token' is set
        if ($ww_access_token === null || (is_array($ww_access_token) && count($ww_access_token) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $ww_access_token when calling setNewAdress'
            );
        }
        // verify the required parameter 'id_user' is set
        if ($id_user === null || (is_array($id_user) && count($id_user) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id_user when calling setNewAdress'
            );
        }
        // verify the required parameter 'type' is set
        if ($type === null || (is_array($type) && count($type) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $type when calling setNewAdress'
            );
        }

        $resourcePath = '/setNewAdress';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($id_user !== null) {
            $queryParams['idUser'] = ObjectSerializer::toQueryValue($id_user, null);
        }
        // query params
        if ($type !== null) {
            $queryParams['type'] = ObjectSerializer::toQueryValue($type, null);
        }
        // header params
        if ($ww_service_id !== null) {
            $headerParams['ww-service-id'] = ObjectSerializer::toHeaderValue($ww_service_id);
        }
        // header params
        if ($ww_access_token !== null) {
            $headerParams['ww-access-token'] = ObjectSerializer::toHeaderValue($ww_access_token);
        }


        // form params
        if ($adress !== null) {
            $formParams['adress'] = ObjectSerializer::toFormValue($adress);
        }
        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/x-www-form-urlencoded']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);
            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation updateAdress
     *
     * Modifier une adresse dans le carnet d'adresses
     *
     * @param  string $ww_service_id Votre service Id (required)
     * @param  string $ww_access_token Un access token valide (required)
     * @param  int $id_adress Id de l&#x27;adresse à modifier. (required)
     * @param  \MerciFacteurApi\Client\Model\AdressInfosAdress $adress adress (optional)
     *
     * @throws \MerciFacteurApi\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \MerciFacteurApi\Client\Model\InlineResponse2002
     */
    public function updateAdress($ww_service_id, $ww_access_token, $id_adress, $adress = null)
    {
        list($response) = $this->updateAdressWithHttpInfo($ww_service_id, $ww_access_token, $id_adress, $adress);
        return $response;
    }

    /**
     * Operation updateAdressWithHttpInfo
     *
     * Modifier une adresse dans le carnet d'adresses
     *
     * @param  string $ww_service_id Votre service Id (required)
     * @param  string $ww_access_token Un access token valide (required)
     * @param  int $id_adress Id de l&#x27;adresse à modifier. (required)
     * @param  \MerciFacteurApi\Client\Model\AdressInfosAdress $adress (optional)
     *
     * @throws \MerciFacteurApi\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \MerciFacteurApi\Client\Model\InlineResponse2002, HTTP status code, HTTP response headers (array of strings)
     */
    public function updateAdressWithHttpInfo($ww_service_id, $ww_access_token, $id_adress, $adress = null)
    {
        $returnType = '\MerciFacteurApi\Client\Model\InlineResponse2002';
        $request = $this->updateAdressRequest($ww_service_id, $ww_access_token, $id_adress, $adress);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string', 'integer', 'bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\MerciFacteurApi\Client\Model\InlineResponse2002',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\MerciFacteurApi\Client\Model\InlineResponse400',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\MerciFacteurApi\Client\Model\InlineResponse400',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation updateAdressAsync
     *
     * Modifier une adresse dans le carnet d'adresses
     *
     * @param  string $ww_service_id Votre service Id (required)
     * @param  string $ww_access_token Un access token valide (required)
     * @param  int $id_adress Id de l&#x27;adresse à modifier. (required)
     * @param  \MerciFacteurApi\Client\Model\AdressInfosAdress $adress (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateAdressAsync($ww_service_id, $ww_access_token, $id_adress, $adress = null)
    {
        return $this->updateAdressAsyncWithHttpInfo($ww_service_id, $ww_access_token, $id_adress, $adress)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation updateAdressAsyncWithHttpInfo
     *
     * Modifier une adresse dans le carnet d'adresses
     *
     * @param  string $ww_service_id Votre service Id (required)
     * @param  string $ww_access_token Un access token valide (required)
     * @param  int $id_adress Id de l&#x27;adresse à modifier. (required)
     * @param  \MerciFacteurApi\Client\Model\AdressInfosAdress $adress (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateAdressAsyncWithHttpInfo($ww_service_id, $ww_access_token, $id_adress, $adress = null)
    {
        $returnType = '\MerciFacteurApi\Client\Model\InlineResponse2002';
        $request = $this->updateAdressRequest($ww_service_id, $ww_access_token, $id_adress, $adress);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'updateAdress'
     *
     * @param  string $ww_service_id Votre service Id (required)
     * @param  string $ww_access_token Un access token valide (required)
     * @param  int $id_adress Id de l&#x27;adresse à modifier. (required)
     * @param  \MerciFacteurApi\Client\Model\AdressInfosAdress $adress (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function updateAdressRequest($ww_service_id, $ww_access_token, $id_adress, $adress = null)
    {
        // verify the required parameter 'ww_service_id' is set
        if ($ww_service_id === null || (is_array($ww_service_id) && count($ww_service_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $ww_service_id when calling updateAdress'
            );
        }
        // verify the required parameter 'ww_access_token' is set
        if ($ww_access_token === null || (is_array($ww_access_token) && count($ww_access_token) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $ww_access_token when calling updateAdress'
            );
        }
        // verify the required parameter 'id_adress' is set
        if ($id_adress === null || (is_array($id_adress) && count($id_adress) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id_adress when calling updateAdress'
            );
        }

        $resourcePath = '/updateAdress';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($id_adress !== null) {
            $queryParams['idAdress'] = ObjectSerializer::toQueryValue($id_adress, null);
        }
        // header params
        if ($ww_service_id !== null) {
            $headerParams['ww-service-id'] = ObjectSerializer::toHeaderValue($ww_service_id);
        }
        // header params
        if ($ww_access_token !== null) {
            $headerParams['ww-access-token'] = ObjectSerializer::toHeaderValue($ww_access_token);
        }


        // form params
        if ($adress !== null) {
            $formParams['adress'] = ObjectSerializer::toFormValue($adress);
        }
        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/x-www-form-urlencoded']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);
            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
