<?php

/**
 * SavApi
 * PHP version 5
 *
 * @category Class
 * @package  MerciFacteurApi\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Merci facteur API
 *
 * Merci facteur PRO vous permet d'envoyer des courriers depuis votre applicatif via son API.     Types de courriers disponibles :   - Lettre de une ou plusieurs pages.  - Carte postale avec ou sans enveloppe  - Carte pliée  - Carte géante  - Carte non pliée  - Photos sur papier brillant    Modes d'envois disponibles :   - Envoi normal (lettre verte)  - Lettre suivie  - Recommandé avec avis de réception      Au sujet des webhooks : [`https://github.com/MerciFacteur/Merci-facteur-API/blob/master/README.md#webhooks`](https://github.com/MerciFacteur/Merci-facteur-API/blob/master/README.md#webhooks)     Librairie PHP et exemples d'intégration : [`https://github.com/MerciFacteur/Merci-facteur-API`](https://github.com/MerciFacteur/Merci-facteur-API)    Infos générales sur l'API : [`https://github.com/MerciFacteur/Merci-facteur-API/blob/master/README.md`](https://github.com/MerciFacteur/Merci-facteur-API/blob/master/README.md)    Plus d'informations sur [`https://www.merci-facteur.com/pro`](https://www.merci-facteur.com/pro)    N'hésitez pas à nous contacter via [`https://www.merci-facteur.com/pro/contact.php`](https://www.merci-facteur.com/pro/contact.php)
 *
 * OpenAPI spec version: 1.2.7
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.51
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace MerciFacteurApi\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use MerciFacteurApi\Client\ApiException;
use MerciFacteurApi\Client\Configuration;
use MerciFacteurApi\Client\HeaderSelector;
use MerciFacteurApi\Client\ObjectSerializer;

/**
 * SavApi Class Doc Comment
 *
 * @category Class
 * @package  MerciFacteurApi\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SavApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation openSavTicket
     *
     * Ouvrir un ticket SAV auprès de Merci facteur
     *
     * @param  string $ww_service_id Votre service Id (required)
     * @param  string $ww_access_token Un access token valide (required)
     * @param  string $your_service_name your_service_name (optional)
     * @param  string $email email (optional)
     * @param  string $reference_courrier reference_courrier (optional)
     * @param  string $sujet sujet (optional)
     * @param  string $message_texte message_texte (optional)
     *
     * @throws \MerciFacteurApi\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \MerciFacteurApi\Client\Model\InlineResponse20015
     */
    public function openSavTicket($ww_service_id, $ww_access_token, $your_service_name = null, $email = null, $reference_courrier = null, $sujet = null, $message_texte = null)
    {
        list($response) = $this->openSavTicketWithHttpInfo($ww_service_id, $ww_access_token, $your_service_name, $email, $reference_courrier, $sujet, $message_texte);
        return $response;
    }

    /**
     * Operation openSavTicketWithHttpInfo
     *
     * Ouvrir un ticket SAV auprès de Merci facteur
     *
     * @param  string $ww_service_id Votre service Id (required)
     * @param  string $ww_access_token Un access token valide (required)
     * @param  string $your_service_name (optional)
     * @param  string $email (optional)
     * @param  string $reference_courrier (optional)
     * @param  string $sujet (optional)
     * @param  string $message_texte (optional)
     *
     * @throws \MerciFacteurApi\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \MerciFacteurApi\Client\Model\InlineResponse20015, HTTP status code, HTTP response headers (array of strings)
     */
    public function openSavTicketWithHttpInfo($ww_service_id, $ww_access_token, $your_service_name = null, $email = null, $reference_courrier = null, $sujet = null, $message_texte = null)
    {
        $returnType = '\MerciFacteurApi\Client\Model\InlineResponse20015';
        $request = $this->openSavTicketRequest($ww_service_id, $ww_access_token, $your_service_name, $email, $reference_courrier, $sujet, $message_texte);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string', 'integer', 'bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\MerciFacteurApi\Client\Model\InlineResponse20015',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\MerciFacteurApi\Client\Model\InlineResponse400',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\MerciFacteurApi\Client\Model\InlineResponse400',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation openSavTicketAsync
     *
     * Ouvrir un ticket SAV auprès de Merci facteur
     *
     * @param  string $ww_service_id Votre service Id (required)
     * @param  string $ww_access_token Un access token valide (required)
     * @param  string $your_service_name (optional)
     * @param  string $email (optional)
     * @param  string $reference_courrier (optional)
     * @param  string $sujet (optional)
     * @param  string $message_texte (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function openSavTicketAsync($ww_service_id, $ww_access_token, $your_service_name = null, $email = null, $reference_courrier = null, $sujet = null, $message_texte = null)
    {
        return $this->openSavTicketAsyncWithHttpInfo($ww_service_id, $ww_access_token, $your_service_name, $email, $reference_courrier, $sujet, $message_texte)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation openSavTicketAsyncWithHttpInfo
     *
     * Ouvrir un ticket SAV auprès de Merci facteur
     *
     * @param  string $ww_service_id Votre service Id (required)
     * @param  string $ww_access_token Un access token valide (required)
     * @param  string $your_service_name (optional)
     * @param  string $email (optional)
     * @param  string $reference_courrier (optional)
     * @param  string $sujet (optional)
     * @param  string $message_texte (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function openSavTicketAsyncWithHttpInfo($ww_service_id, $ww_access_token, $your_service_name = null, $email = null, $reference_courrier = null, $sujet = null, $message_texte = null)
    {
        $returnType = '\MerciFacteurApi\Client\Model\InlineResponse20015';
        $request = $this->openSavTicketRequest($ww_service_id, $ww_access_token, $your_service_name, $email, $reference_courrier, $sujet, $message_texte);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'openSavTicket'
     *
     * @param  string $ww_service_id Votre service Id (required)
     * @param  string $ww_access_token Un access token valide (required)
     * @param  string $your_service_name (optional)
     * @param  string $email (optional)
     * @param  string $reference_courrier (optional)
     * @param  string $sujet (optional)
     * @param  string $message_texte (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function openSavTicketRequest($ww_service_id, $ww_access_token, $your_service_name = null, $email = null, $reference_courrier = null, $sujet = null, $message_texte = null)
    {
        // verify the required parameter 'ww_service_id' is set
        if ($ww_service_id === null || (is_array($ww_service_id) && count($ww_service_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $ww_service_id when calling openSavTicket'
            );
        }
        // verify the required parameter 'ww_access_token' is set
        if ($ww_access_token === null || (is_array($ww_access_token) && count($ww_access_token) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $ww_access_token when calling openSavTicket'
            );
        }

        $resourcePath = '/openSavTicket';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // header params
        if ($ww_service_id !== null) {
            $headerParams['ww-service-id'] = ObjectSerializer::toHeaderValue($ww_service_id);
        }
        // header params
        if ($ww_access_token !== null) {
            $headerParams['ww-access-token'] = ObjectSerializer::toHeaderValue($ww_access_token);
        }


        // form params
        if ($your_service_name !== null) {
            $formParams['yourServiceName'] = ObjectSerializer::toFormValue($your_service_name);
        }
        // form params
        if ($email !== null) {
            $formParams['email'] = ObjectSerializer::toFormValue($email);
        }
        // form params
        if ($reference_courrier !== null) {
            $formParams['referenceCourrier'] = ObjectSerializer::toFormValue($reference_courrier);
        }
        // form params
        if ($sujet !== null) {
            $formParams['sujet'] = ObjectSerializer::toFormValue($sujet);
        }
        // form params
        if ($message_texte !== null) {
            $formParams['messageTexte'] = ObjectSerializer::toFormValue($message_texte);
        }
        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/x-www-form-urlencoded']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);
            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
