/*
 * Merci facteur API
 * Merci facteur PRO vous permet d'envoyer des courriers depuis votre applicatif via son API.     Types de courriers disponibles :   - Lettre de une ou plusieurs pages.  - Carte postale avec ou sans enveloppe  - Carte pliée  - Carte géante  - Carte non pliée  - Photos sur papier brillant    Modes d'envois disponibles :   - Envoi normal (lettre verte)  - Lettre suivie  - Recommandé avec avis de réception      Au sujet des webhooks : [`https://github.com/MerciFacteur/Merci-facteur-API/blob/master/README.md#webhooks`](https://github.com/MerciFacteur/Merci-facteur-API/blob/master/README.md#webhooks)     Librairie PHP et exemples d'intégration : [`https://github.com/MerciFacteur/Merci-facteur-API`](https://github.com/MerciFacteur/Merci-facteur-API)    Infos générales sur l'API : [`https://github.com/MerciFacteur/Merci-facteur-API/blob/master/README.md`](https://github.com/MerciFacteur/Merci-facteur-API/blob/master/README.md)    Plus d'informations sur [`https://www.merci-facteur.com/pro`](https://www.merci-facteur.com/pro)    N'hésitez pas à nous contacter via [`https://www.merci-facteur.com/pro/contact.php`](https://www.merci-facteur.com/pro/contact.php)
 *
 * OpenAPI spec version: 1.2.7
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.50
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The AdressInfosAdress model module.
 * @module model/AdressInfosAdress
 * @version 1.2.7
 */
export class AdressInfosAdress {
  /**
   * Constructs a new <code>AdressInfosAdress</code>.
   * @alias module:model/AdressInfosAdress
   * @class
   * @param cp {String} Code postal de l'adresse
   * @param ville {String} Ville de l'adresse
   * @param pays {String} Pays avec une orthographe conforme (cf. getCountry)
   */
  constructor(cp, ville, pays) {
    this.cp = cp;
    this.ville = ville;
    this.pays = pays;
  }

  /**
   * Constructs a <code>AdressInfosAdress</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AdressInfosAdress} obj Optional instance to populate.
   * @return {module:model/AdressInfosAdress} The populated <code>AdressInfosAdress</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new AdressInfosAdress();
      if (data.hasOwnProperty('logo'))
        obj.logo = ApiClient.convertToType(data['logo'], 'String');
      if (data.hasOwnProperty('civilite'))
        obj.civilite = ApiClient.convertToType(data['civilite'], 'String');
      if (data.hasOwnProperty('nom'))
        obj.nom = ApiClient.convertToType(data['nom'], 'String');
      if (data.hasOwnProperty('prenom'))
        obj.prenom = ApiClient.convertToType(data['prenom'], 'String');
      if (data.hasOwnProperty('societe'))
        obj.societe = ApiClient.convertToType(data['societe'], 'String');
      if (data.hasOwnProperty('adresse1'))
        obj.adresse1 = ApiClient.convertToType(data['adresse1'], 'String');
      if (data.hasOwnProperty('adresse2'))
        obj.adresse2 = ApiClient.convertToType(data['adresse2'], 'String');
      if (data.hasOwnProperty('adresse3'))
        obj.adresse3 = ApiClient.convertToType(data['adresse3'], 'String');
      if (data.hasOwnProperty('cp'))
        obj.cp = ApiClient.convertToType(data['cp'], 'String');
      if (data.hasOwnProperty('ville'))
        obj.ville = ApiClient.convertToType(data['ville'], 'String');
      if (data.hasOwnProperty('pays'))
        obj.pays = ApiClient.convertToType(data['pays'], 'String');
      if (data.hasOwnProperty('phone'))
        obj.phone = ApiClient.convertToType(data['phone'], 'String');
      if (data.hasOwnProperty('email'))
        obj.email = ApiClient.convertToType(data['email'], 'String');
      if (data.hasOwnProperty('consent'))
        obj.consent = ApiClient.convertToType(data['consent'], 'Number');
    }
    return obj;
  }
}

/**
 * Url du logo (uniquement pour les expéditeurs)
 * @member {String} logo
 */
AdressInfosAdress.prototype.logo = undefined;

/**
 * Civilité du contact
 * @member {String} civilite
 */
AdressInfosAdress.prototype.civilite = undefined;

/**
 * Nom du contact (doit être rempli si societe est vide)
 * @member {String} nom
 */
AdressInfosAdress.prototype.nom = undefined;

/**
 * Prénom du contact
 * @member {String} prenom
 */
AdressInfosAdress.prototype.prenom = undefined;

/**
 * Société du contact (doit être rempli si le nom est vide)
 * @member {String} societe
 */
AdressInfosAdress.prototype.societe = undefined;

/**
 * Première ligne de l'adresse (exemple : la rue)
 * @member {String} adresse1
 */
AdressInfosAdress.prototype.adresse1 = undefined;

/**
 * Seconde ligne de l'adresse (exemple : le lieu-dit)
 * @member {String} adresse2
 */
AdressInfosAdress.prototype.adresse2 = undefined;

/**
 * Troisième ligne de l'adresse (exemple : la boite postale)
 * @member {String} adresse3
 */
AdressInfosAdress.prototype.adresse3 = undefined;

/**
 * Code postal de l'adresse
 * @member {String} cp
 */
AdressInfosAdress.prototype.cp = undefined;

/**
 * Ville de l'adresse
 * @member {String} ville
 */
AdressInfosAdress.prototype.ville = undefined;

/**
 * Pays avec une orthographe conforme (cf. getCountry)
 * @member {String} pays
 */
AdressInfosAdress.prototype.pays = undefined;

/**
 * Le téléphone mobile du destinataire en cas d'envoi de recommandé électronique avec OTP SMS (format +33628749452)
 * @member {String} phone
 */
AdressInfosAdress.prototype.phone = undefined;

/**
 * Adesse email du destinataire ou de l'expéditeur en cas d'envoi de recommandé électronique
 * @member {String} email
 */
AdressInfosAdress.prototype.email = undefined;

/**
 * Pour le destinataire dans le cas d'un envoi de recommandé électronique, il s'agit du consentement donné par le destinataire (doit être =1 pour permettre l'envoi d'un recommandé électronique)
 * @member {Number} consent
 */
AdressInfosAdress.prototype.consent = undefined;

