/*
 * Merci facteur API
 * Merci facteur PRO vous permet d'envoyer des courriers depuis votre applicatif via son API.     Types de courriers disponibles :   - Lettre de une ou plusieurs pages.  - Carte postale avec ou sans enveloppe  - Carte pliée  - Carte géante  - Carte non pliée  - Photos sur papier brillant    Modes d'envois disponibles :   - Envoi normal (lettre verte)  - Lettre suivie  - Recommandé avec avis de réception      Au sujet des webhooks : [`https://github.com/MerciFacteur/Merci-facteur-API/blob/master/README.md#webhooks`](https://github.com/MerciFacteur/Merci-facteur-API/blob/master/README.md#webhooks)     Librairie PHP et exemples d'intégration : [`https://github.com/MerciFacteur/Merci-facteur-API`](https://github.com/MerciFacteur/Merci-facteur-API)    Infos générales sur l'API : [`https://github.com/MerciFacteur/Merci-facteur-API/blob/master/README.md`](https://github.com/MerciFacteur/Merci-facteur-API/blob/master/README.md)    Plus d'informations sur [`https://www.merci-facteur.com/pro`](https://www.merci-facteur.com/pro)    N'hésitez pas à nous contacter via [`https://www.merci-facteur.com/pro/contact.php`](https://www.merci-facteur.com/pro/contact.php)
 *
 * OpenAPI spec version: 1.2.7
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.50
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The AdressSendCourrier model module.
 * @module model/AdressSendCourrier
 * @version 1.2.7
 */
export class AdressSendCourrier {
  /**
   * Constructs a new <code>AdressSendCourrier</code>.
   * Les Id des adresses d&#x27;expéditeur et de destinataire (1 expéditeur, 1 ou plusieurs destinataires). OU directement les adresses dans un objet si vous ne souhaitez pas utiliser le carnet d&#x27;adresses (plus d&#x27;infos ici : https://github.com/MerciFacteur/Merci-facteur-API#format-des-adresses-lors-de-lenvoi-dun-courrier-).
   * @alias module:model/AdressSendCourrier
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>AdressSendCourrier</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AdressSendCourrier} obj Optional instance to populate.
   * @return {module:model/AdressSendCourrier} The populated <code>AdressSendCourrier</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new AdressSendCourrier();
      if (data.hasOwnProperty('exp'))
        obj.exp = ApiClient.convertToType(data['exp'], 'String');
      if (data.hasOwnProperty('dest'))
        obj.dest = ApiClient.convertToType(data['dest'], ['String']);
    }
    return obj;
  }
}

/**
 * Indiquez ici l'id de l'expéditeur OU un object contenant directement l'adresse de l'expéditeur.
 * @member {String} exp
 */
AdressSendCourrier.prototype.exp = undefined;

/**
 * Indiquez ici un tableau avec les ID des destinataires OU un tableau d'objects contenant directement les adresses des destinataires.
 * @member {Array.<String>} dest
 */
AdressSendCourrier.prototype.dest = undefined;

