/*
 * Merci facteur API
 * Merci facteur PRO vous permet d'envoyer des courriers depuis votre applicatif via son API.     Types de courriers disponibles :   - Lettre de une ou plusieurs pages.  - Carte postale avec ou sans enveloppe  - Carte pliée  - Carte géante  - Carte non pliée  - Photos sur papier brillant    Modes d'envois disponibles :   - Envoi normal (lettre verte)  - Lettre suivie  - Recommandé avec avis de réception      Au sujet des webhooks : [`https://github.com/MerciFacteur/Merci-facteur-API/blob/master/README.md#webhooks`](https://github.com/MerciFacteur/Merci-facteur-API/blob/master/README.md#webhooks)     Librairie PHP et exemples d'intégration : [`https://github.com/MerciFacteur/Merci-facteur-API`](https://github.com/MerciFacteur/Merci-facteur-API)    Infos générales sur l'API : [`https://github.com/MerciFacteur/Merci-facteur-API/blob/master/README.md`](https://github.com/MerciFacteur/Merci-facteur-API/blob/master/README.md)    Plus d'informations sur [`https://www.merci-facteur.com/pro`](https://www.merci-facteur.com/pro)    N'hésitez pas à nous contacter via [`https://www.merci-facteur.com/pro/contact.php`](https://www.merci-facteur.com/pro/contact.php)
 *
 * OpenAPI spec version: 1.2.7
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.50
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {InlineResponse20018QuotasCredit} from './InlineResponse20018QuotasCredit';
import {InlineResponse20018QuotasPages} from './InlineResponse20018QuotasPages';
import {InlineResponse20018QuotasPlan} from './InlineResponse20018QuotasPlan';

/**
 * The InlineResponse20018Quotas model module.
 * @module model/InlineResponse20018Quotas
 * @version 1.2.7
 */
export class InlineResponse20018Quotas {
  /**
   * Constructs a new <code>InlineResponse20018Quotas</code>.
   * Objet contenant les infos des quotas du compte.
   * @alias module:model/InlineResponse20018Quotas
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>InlineResponse20018Quotas</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse20018Quotas} obj Optional instance to populate.
   * @return {module:model/InlineResponse20018Quotas} The populated <code>InlineResponse20018Quotas</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new InlineResponse20018Quotas();
      if (data.hasOwnProperty('plan'))
        obj.plan = InlineResponse20018QuotasPlan.constructFromObject(data['plan']);
      if (data.hasOwnProperty('credit'))
        obj.credit = InlineResponse20018QuotasCredit.constructFromObject(data['credit']);
      if (data.hasOwnProperty('pages'))
        obj.pages = InlineResponse20018QuotasPages.constructFromObject(data['pages']);
    }
    return obj;
  }
}

/**
 * @member {module:model/InlineResponse20018QuotasPlan} plan
 */
InlineResponse20018Quotas.prototype.plan = undefined;

/**
 * @member {module:model/InlineResponse20018QuotasCredit} credit
 */
InlineResponse20018Quotas.prototype.credit = undefined;

/**
 * @member {module:model/InlineResponse20018QuotasPages} pages
 */
InlineResponse20018Quotas.prototype.pages = undefined;

