/*
 * Merci facteur API
 * Merci facteur PRO vous permet d'envoyer des courriers depuis votre applicatif via son API.     Types de courriers disponibles :   - Lettre de une ou plusieurs pages.  - Carte postale avec ou sans enveloppe  - Carte pliée  - Carte géante  - Carte non pliée  - Photos sur papier brillant    Modes d'envois disponibles :   - Envoi normal (lettre verte)  - Lettre suivie  - Recommandé avec avis de réception      Au sujet des webhooks : [`https://github.com/MerciFacteur/Merci-facteur-API/blob/master/README.md#webhooks`](https://github.com/MerciFacteur/Merci-facteur-API/blob/master/README.md#webhooks)     Librairie PHP et exemples d'intégration : [`https://github.com/MerciFacteur/Merci-facteur-API`](https://github.com/MerciFacteur/Merci-facteur-API)    Infos générales sur l'API : [`https://github.com/MerciFacteur/Merci-facteur-API/blob/master/README.md`](https://github.com/MerciFacteur/Merci-facteur-API/blob/master/README.md)    Plus d'informations sur [`https://www.merci-facteur.com/pro`](https://www.merci-facteur.com/pro)    N'hésitez pas à nous contacter via [`https://www.merci-facteur.com/pro/contact.php`](https://www.merci-facteur.com/pro/contact.php)
 *
 * OpenAPI spec version: 1.2.7
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.50
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {InlineResponse20012Detail} from './InlineResponse20012Detail';
import {InlineResponse20012General} from './InlineResponse20012General';

/**
 * The InlineResponse20012Envoi model module.
 * @module model/InlineResponse20012Envoi
 * @version 1.2.7
 */
export class InlineResponse20012Envoi {
  /**
   * Constructs a new <code>InlineResponse20012Envoi</code>.
   * @alias module:model/InlineResponse20012Envoi
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>InlineResponse20012Envoi</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse20012Envoi} obj Optional instance to populate.
   * @return {module:model/InlineResponse20012Envoi} The populated <code>InlineResponse20012Envoi</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new InlineResponse20012Envoi();
      if (data.hasOwnProperty('general'))
        obj.general = ApiClient.convertToType(data['general'], [InlineResponse20012General]);
      if (data.hasOwnProperty('detail'))
        obj.detail = ApiClient.convertToType(data['detail'], [InlineResponse20012Detail]);
    }
    return obj;
  }
}

/**
 * @member {Array.<module:model/InlineResponse20012General>} general
 */
InlineResponse20012Envoi.prototype.general = undefined;

/**
 * @member {Array.<module:model/InlineResponse20012Detail>} detail
 */
InlineResponse20012Envoi.prototype.detail = undefined;

