/*
 * Merci facteur API
 * Merci facteur PRO vous permet d'envoyer des courriers depuis votre applicatif via son API.     Types de courriers disponibles :   - Lettre de une ou plusieurs pages.  - Carte postale avec ou sans enveloppe  - Carte pliée  - Carte géante  - Carte non pliée  - Photos sur papier brillant    Modes d'envois disponibles :   - Envoi normal (lettre verte)  - Lettre suivie  - Recommandé avec avis de réception      Au sujet des webhooks : [`https://github.com/MerciFacteur/Merci-facteur-API/blob/master/README.md#webhooks`](https://github.com/MerciFacteur/Merci-facteur-API/blob/master/README.md#webhooks)     Librairie PHP et exemples d'intégration : [`https://github.com/MerciFacteur/Merci-facteur-API`](https://github.com/MerciFacteur/Merci-facteur-API)    Infos générales sur l'API : [`https://github.com/MerciFacteur/Merci-facteur-API/blob/master/README.md`](https://github.com/MerciFacteur/Merci-facteur-API/blob/master/README.md)    Plus d'informations sur [`https://www.merci-facteur.com/pro`](https://www.merci-facteur.com/pro)    N'hésitez pas à nous contacter via [`https://www.merci-facteur.com/pro/contact.php`](https://www.merci-facteur.com/pro/contact.php)
 *
 * OpenAPI spec version: 1.2.7
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.50
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {InlineResponse20011Contenu} from './InlineResponse20011Contenu';
import {InlineResponse20011Total} from './InlineResponse20011Total';

/**
 * The InlineResponse20011Amount model module.
 * @module model/InlineResponse20011Amount
 * @version 1.2.7
 */
export class InlineResponse20011Amount {
  /**
   * Constructs a new <code>InlineResponse20011Amount</code>.
   * @alias module:model/InlineResponse20011Amount
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>InlineResponse20011Amount</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse20011Amount} obj Optional instance to populate.
   * @return {module:model/InlineResponse20011Amount} The populated <code>InlineResponse20011Amount</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new InlineResponse20011Amount();
      if (data.hasOwnProperty('contenu'))
        obj.contenu = ApiClient.convertToType(data['contenu'], [InlineResponse20011Contenu]);
      if (data.hasOwnProperty('affranchissement'))
        obj.affranchissement = ApiClient.convertToType(data['affranchissement'], 'String');
      if (data.hasOwnProperty('total'))
        obj.total = ApiClient.convertToType(data['total'], [InlineResponse20011Total]);
    }
    return obj;
  }
}

/**
 * @member {Array.<module:model/InlineResponse20011Contenu>} contenu
 */
InlineResponse20011Amount.prototype.contenu = undefined;

/**
 * Sous-total de l'affranchissement
 * @member {String} affranchissement
 */
InlineResponse20011Amount.prototype.affranchissement = undefined;

/**
 * Montant total facturé
 * @member {Array.<module:model/InlineResponse20011Total>} total
 */
InlineResponse20011Amount.prototype.total = undefined;

