/*
 * Merci facteur API
 * Merci facteur PRO vous permet d'envoyer des courriers depuis votre applicatif via son API.     Types de courriers disponibles :   - Lettre de une ou plusieurs pages.  - Carte postale avec ou sans enveloppe  - Carte pliée  - Carte géante  - Carte non pliée  - Photos sur papier brillant    Modes d'envois disponibles :   - Envoi normal (lettre verte)  - Lettre suivie  - Recommandé avec avis de réception      Au sujet des webhooks : [`https://github.com/MerciFacteur/Merci-facteur-API/blob/master/README.md#webhooks`](https://github.com/MerciFacteur/Merci-facteur-API/blob/master/README.md#webhooks)     Librairie PHP et exemples d'intégration : [`https://github.com/MerciFacteur/Merci-facteur-API`](https://github.com/MerciFacteur/Merci-facteur-API)    Infos générales sur l'API : [`https://github.com/MerciFacteur/Merci-facteur-API/blob/master/README.md`](https://github.com/MerciFacteur/Merci-facteur-API/blob/master/README.md)    Plus d'informations sur [`https://www.merci-facteur.com/pro`](https://www.merci-facteur.com/pro)    N'hésitez pas à nous contacter via [`https://www.merci-facteur.com/pro/contact.php`](https://www.merci-facteur.com/pro/contact.php)
 *
 * OpenAPI spec version: 1.2.7
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.50
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {InlineResponse2007Adress0} from './InlineResponse2007Adress0';

/**
 * The InlineResponse2007Adress model module.
 * @module model/InlineResponse2007Adress
 * @version 1.2.7
 */
export class InlineResponse2007Adress {
  /**
   * Constructs a new <code>InlineResponse2007Adress</code>.
   * Chaque adresse listée sous une clé correspondant à son ID
   * @alias module:model/InlineResponse2007Adress
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>InlineResponse2007Adress</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse2007Adress} obj Optional instance to populate.
   * @return {module:model/InlineResponse2007Adress} The populated <code>InlineResponse2007Adress</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new InlineResponse2007Adress();
      if (data.hasOwnProperty('0'))
        obj._0 = InlineResponse2007Adress0.constructFromObject(data['0']);
    }
    return obj;
  }
}

/**
 * @member {module:model/InlineResponse2007Adress0} _0
 */
InlineResponse2007Adress.prototype._0 = undefined;

