/*
 * Merci facteur API
 * Merci facteur PRO vous permet d'envoyer des courriers depuis votre applicatif via son API.     Types de courriers disponibles :   - Lettre de une ou plusieurs pages.  - Carte postale avec ou sans enveloppe  - Carte pliée  - Carte géante  - Carte non pliée  - Photos sur papier brillant    Modes d'envois disponibles :   - Envoi normal (lettre verte)  - Lettre suivie  - Recommandé avec avis de réception      Au sujet des webhooks : [`https://github.com/MerciFacteur/Merci-facteur-API/blob/master/README.md#webhooks`](https://github.com/MerciFacteur/Merci-facteur-API/blob/master/README.md#webhooks)     Librairie PHP et exemples d'intégration : [`https://github.com/MerciFacteur/Merci-facteur-API`](https://github.com/MerciFacteur/Merci-facteur-API)    Infos générales sur l'API : [`https://github.com/MerciFacteur/Merci-facteur-API/blob/master/README.md`](https://github.com/MerciFacteur/Merci-facteur-API/blob/master/README.md)    Plus d'informations sur [`https://www.merci-facteur.com/pro`](https://www.merci-facteur.com/pro)    N'hésitez pas à nous contacter via [`https://www.merci-facteur.com/pro/contact.php`](https://www.merci-facteur.com/pro/contact.php)
 *
 * OpenAPI spec version: 1.2.7
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.50
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The InlineResponse20010AffranchissementPAYS model module.
 * @module model/InlineResponse20010AffranchissementPAYS
 * @version 1.2.7
 */
export class InlineResponse20010AffranchissementPAYS {
  /**
   * Constructs a new <code>InlineResponse20010AffranchissementPAYS</code>.
   * Object contenant le montant d&#x27;affranchissement pour ce pays ainsi que la zone géographique.
   * @alias module:model/InlineResponse20010AffranchissementPAYS
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>InlineResponse20010AffranchissementPAYS</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse20010AffranchissementPAYS} obj Optional instance to populate.
   * @return {module:model/InlineResponse20010AffranchissementPAYS} The populated <code>InlineResponse20010AffranchissementPAYS</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new InlineResponse20010AffranchissementPAYS();
      if (data.hasOwnProperty('amount'))
        obj.amount = ApiClient.convertToType(data['amount'], 'String');
      if (data.hasOwnProperty('zone'))
        obj.zone = ApiClient.convertToType(data['zone'], 'String');
    }
    return obj;
  }
}

/**
 * montant HT de l'affranchissement
 * @member {String} amount
 */
InlineResponse20010AffranchissementPAYS.prototype.amount = undefined;

/**
 * Zone géographique du pays (fr, z1, z2, om1, om2)
 * @member {String} zone
 */
InlineResponse20010AffranchissementPAYS.prototype.zone = undefined;

