/*
 * Merci facteur API
 * Merci facteur PRO vous permet d'envoyer des courriers depuis votre applicatif via son API.     Types de courriers disponibles :   - Lettre de une ou plusieurs pages.  - Carte postale avec ou sans enveloppe  - Carte pliée  - Carte géante  - Carte non pliée  - Photos sur papier brillant    Modes d'envois disponibles :   - Envoi normal (lettre verte)  - Lettre suivie  - Recommandé avec avis de réception      Au sujet des webhooks : [`https://github.com/MerciFacteur/Merci-facteur-API/blob/master/README.md#webhooks`](https://github.com/MerciFacteur/Merci-facteur-API/blob/master/README.md#webhooks)     Librairie PHP et exemples d'intégration : [`https://github.com/MerciFacteur/Merci-facteur-API`](https://github.com/MerciFacteur/Merci-facteur-API)    Infos générales sur l'API : [`https://github.com/MerciFacteur/Merci-facteur-API/blob/master/README.md`](https://github.com/MerciFacteur/Merci-facteur-API/blob/master/README.md)    Plus d'informations sur [`https://www.merci-facteur.com/pro`](https://www.merci-facteur.com/pro)    N'hésitez pas à nous contacter via [`https://www.merci-facteur.com/pro/contact.php`](https://www.merci-facteur.com/pro/contact.php)
 *
 * OpenAPI spec version: 1.2.7
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.50
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The InlineResponse2009PriceDetail model module.
 * @module model/InlineResponse2009PriceDetail
 * @version 1.2.7
 */
export class InlineResponse2009PriceDetail {
  /**
   * Constructs a new <code>InlineResponse2009PriceDetail</code>.
   * @alias module:model/InlineResponse2009PriceDetail
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>InlineResponse2009PriceDetail</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse2009PriceDetail} obj Optional instance to populate.
   * @return {module:model/InlineResponse2009PriceDetail} The populated <code>InlineResponse2009PriceDetail</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new InlineResponse2009PriceDetail();
      if (data.hasOwnProperty('affranchissement'))
        obj.affranchissement = ApiClient.convertToType(data['affranchissement'], 'String');
      if (data.hasOwnProperty('letter'))
        obj.letter = ApiClient.convertToType(data['letter'], 'String');
      if (data.hasOwnProperty('card'))
        obj.card = ApiClient.convertToType(data['card'], 'String');
    }
    return obj;
  }
}

/**
 * Montant total de l'affranchissement (ht, tva=0)
 * @member {String} affranchissement
 */
InlineResponse2009PriceDetail.prototype.affranchissement = undefined;

/**
 * Montant total du contenu lettres (ht, tva=tx standard)
 * @member {String} letter
 */
InlineResponse2009PriceDetail.prototype.letter = undefined;

/**
 * Montant total du contenu cartes (ht, tva=tx standard)
 * @member {String} card
 */
InlineResponse2009PriceDetail.prototype.card = undefined;

