/*
 * Merci facteur API
 * Merci facteur PRO vous permet d'envoyer des courriers depuis votre applicatif via son API.     Types de courriers disponibles :   - Lettre de une ou plusieurs pages.  - Carte postale avec ou sans enveloppe  - Carte pliée  - Carte géante  - Carte non pliée  - Photos sur papier brillant    Modes d'envois disponibles :   - Envoi normal (lettre verte)  - Lettre suivie  - Recommandé avec avis de réception      Au sujet des webhooks : [`https://github.com/MerciFacteur/Merci-facteur-API/blob/master/README.md#webhooks`](https://github.com/MerciFacteur/Merci-facteur-API/blob/master/README.md#webhooks)     Librairie PHP et exemples d'intégration : [`https://github.com/MerciFacteur/Merci-facteur-API`](https://github.com/MerciFacteur/Merci-facteur-API)    Infos générales sur l'API : [`https://github.com/MerciFacteur/Merci-facteur-API/blob/master/README.md`](https://github.com/MerciFacteur/Merci-facteur-API/blob/master/README.md)    Plus d'informations sur [`https://www.merci-facteur.com/pro`](https://www.merci-facteur.com/pro)    N'hésitez pas à nous contacter via [`https://www.merci-facteur.com/pro/contact.php`](https://www.merci-facteur.com/pro/contact.php)
 *
 * OpenAPI spec version: 1.2.7
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.50
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The SendCourrierContentCardText model module.
 * @module model/SendCourrierContentCardText
 * @version 1.2.7
 */
export class SendCourrierContentCardText {
  /**
   * Constructs a new <code>SendCourrierContentCardText</code>.
   * Informations concernant le texte de la carte
   * @alias module:model/SendCourrierContentCardText
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>SendCourrierContentCardText</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SendCourrierContentCardText} obj Optional instance to populate.
   * @return {module:model/SendCourrierContentCardText} The populated <code>SendCourrierContentCardText</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new SendCourrierContentCardText();
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
      if (data.hasOwnProperty('value'))
        obj.value = ApiClient.convertToType(data['value'], 'String');
    }
    return obj;
  }
}

/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
SendCourrierContentCardText.TypeEnum = {
  /**
   * value: "html"
   * @const
   */
  html: "html",

  /**
   * value: "customimg"
   * @const
   */
  customimg: "customimg",

  /**
   * value: "base64"
   * @const
   */
  base64: "base64"
};
/**
 * Type de visuel : html (code html), base64 (image), customimg (image)
 * @member {module:model/SendCourrierContentCardText.TypeEnum} type
 */
SendCourrierContentCardText.prototype.type = undefined;

/**
 * Si type=html, alors value=html contenant le texte à imprimer sur le dos la carte. Si type=base64, alors value=une base64 contenant une image à imprimer sur le dos de la carte. Si type=customimg, alors value=une URL d'une image à imprimer sur le dos de la carte.
 * @member {String} value
 */
SendCourrierContentCardText.prototype.value = undefined;

