/*
 * Merci facteur API
 * Merci facteur PRO vous permet d'envoyer des courriers depuis votre applicatif via son API.     Types de courriers disponibles :   - Lettre de une ou plusieurs pages.  - Carte postale avec ou sans enveloppe  - Carte pliée  - Carte géante  - Carte non pliée  - Photos sur papier brillant    Modes d'envois disponibles :   - Envoi normal (lettre verte)  - Lettre suivie  - Recommandé avec avis de réception      Au sujet des webhooks : [`https://github.com/MerciFacteur/Merci-facteur-API/blob/master/README.md#webhooks`](https://github.com/MerciFacteur/Merci-facteur-API/blob/master/README.md#webhooks)     Librairie PHP et exemples d'intégration : [`https://github.com/MerciFacteur/Merci-facteur-API`](https://github.com/MerciFacteur/Merci-facteur-API)    Infos générales sur l'API : [`https://github.com/MerciFacteur/Merci-facteur-API/blob/master/README.md`](https://github.com/MerciFacteur/Merci-facteur-API/blob/master/README.md)    Plus d'informations sur [`https://www.merci-facteur.com/pro`](https://www.merci-facteur.com/pro)    N'hésitez pas à nous contacter via [`https://www.merci-facteur.com/pro/contact.php`](https://www.merci-facteur.com/pro/contact.php)
 *
 * OpenAPI spec version: 1.2.7
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.50
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Base64FilesSendCourrier} from './Base64FilesSendCourrier';
import {FilesSendCourrier} from './FilesSendCourrier';

/**
 * The SendCourrierContentLetter model module.
 * @module model/SendCourrierContentLetter
 * @version 1.2.7
 */
export class SendCourrierContentLetter {
  /**
   * Constructs a new <code>SendCourrierContentLetter</code>.
   * Définition du contenu de la lettre, envoyer une chaine vide si pas de lettre dans ce courrier (&#x3D;&#x27;&#x27;)
   * @alias module:model/SendCourrierContentLetter
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>SendCourrierContentLetter</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SendCourrierContentLetter} obj Optional instance to populate.
   * @return {module:model/SendCourrierContentLetter} The populated <code>SendCourrierContentLetter</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new SendCourrierContentLetter();
      if (data.hasOwnProperty('files'))
        obj.files = FilesSendCourrier.constructFromObject(data['files']);
      if (data.hasOwnProperty('base64files'))
        obj.base64files = Base64FilesSendCourrier.constructFromObject(data['base64files']);
      if (data.hasOwnProperty('final_filename'))
        obj.finalFilename = ApiClient.convertToType(data['final_filename'], 'String');
      if (data.hasOwnProperty('print_sides'))
        obj.printSides = ApiClient.convertToType(data['print_sides'], 'String');
    }
    return obj;
  }
}

/**
 * @member {module:model/FilesSendCourrier} files
 */
SendCourrierContentLetter.prototype.files = undefined;

/**
 * @member {module:model/Base64FilesSendCourrier} base64files
 */
SendCourrierContentLetter.prototype.base64files = undefined;

/**
 * Facultatif, maximum 50 caractères, vous pouvez spécifier le nom de fichier que vous souhaitez pour votre lettre. Ne mettez pas d''extension, '.pdf' sera ajouté à la fin. Il sera visible dans votre interface Merci facteur Pro pour faciliter vos recherches. Dans le cas d'envois recommandés électroniques (ERE), ce nom de fichier sera visible par le destinataire.
 * @member {String} finalFilename
 */
SendCourrierContentLetter.prototype.finalFilename = undefined;

/**
 * Allowed values for the <code>printSides</code> property.
 * @enum {String}
 * @readonly
 */
SendCourrierContentLetter.PrintSidesEnum = {
  /**
   * value: "recto"
   * @const
   */
  recto: "recto",

  /**
   * value: "rectoverso"
   * @const
   */
  rectoverso: "rectoverso",

  /**
   * value: "distinctrectoverso"
   * @const
   */
  distinctrectoverso: "distinctrectoverso"
};
/**
 * rectoverso si vous souhaitez une impression recto/verso, ou recto si vous souhaitez une impression recto simple, ou distinctrectoverso si vous souhaitez une impression recto/verso et que nous insérions une page blanche après les fichiers au nombre de pages impair.
 * @member {module:model/SendCourrierContentLetter.PrintSidesEnum} printSides
 */
SendCourrierContentLetter.prototype.printSides = undefined;

