/*
 * Merci facteur API
 * Merci facteur PRO vous permet d'envoyer des courriers depuis votre applicatif via son API.     Types de courriers disponibles :   - Lettre de une ou plusieurs pages.  - Carte postale avec ou sans enveloppe  - Carte pliée  - Carte géante  - Carte non pliée  - Photos sur papier brillant    Modes d'envois disponibles :   - Envoi normal (lettre verte)  - Lettre suivie  - Recommandé avec avis de réception      Au sujet des webhooks : [`https://github.com/MerciFacteur/Merci-facteur-API/blob/master/README.md#webhooks`](https://github.com/MerciFacteur/Merci-facteur-API/blob/master/README.md#webhooks)     Librairie PHP et exemples d'intégration : [`https://github.com/MerciFacteur/Merci-facteur-API`](https://github.com/MerciFacteur/Merci-facteur-API)    Infos générales sur l'API : [`https://github.com/MerciFacteur/Merci-facteur-API/blob/master/README.md`](https://github.com/MerciFacteur/Merci-facteur-API/blob/master/README.md)    Plus d'informations sur [`https://www.merci-facteur.com/pro`](https://www.merci-facteur.com/pro)    N'hésitez pas à nous contacter via [`https://www.merci-facteur.com/pro/contact.php`](https://www.merci-facteur.com/pro/contact.php)
 *
 * OpenAPI spec version: 1.2.7
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.50
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The SendCourrierAnonymize model module.
 * @module model/SendCourrierAnonymize
 * @version 1.2.7
 */
export class SendCourrierAnonymize {
  /**
   * Constructs a new <code>SendCourrierAnonymize</code>.
   * Facultatif, permet de demander la suppression d\\&#x27;éléments du courrier un certain délai (en nombre de jours) après l\\&#x27;impression du courrier. A utiliser si vous ne souhaitez pas que les données des courriers soient conservées sur les serveurs de Merci Facteur. Exemple de valeur : {\&quot;delay\&quot;:15,\&quot;target\&quot;:[\&quot;content\&quot;,\&quot;exp\&quot;,\&quot;dest\&quot;]} (plus d\\&#x27;infos ici : https://github.com/MerciFacteur/Merci-facteur-API/#anonymisation)
   * @alias module:model/SendCourrierAnonymize
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>SendCourrierAnonymize</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SendCourrierAnonymize} obj Optional instance to populate.
   * @return {module:model/SendCourrierAnonymize} The populated <code>SendCourrierAnonymize</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new SendCourrierAnonymize();
      if (data.hasOwnProperty('delay'))
        obj.delay = ApiClient.convertToType(data['delay'], 'Number');
      if (data.hasOwnProperty('target'))
        obj.target = ApiClient.convertToType(data['target'], ['String']);
    }
    return obj;
  }
}

/**
 * Délai en nombre de jours (min. 1, max. 400) à compter de l'impression, après lesquels vous souhaitez que l'anonymisation ai lieu.
 * @member {Number} delay
 * @default 10
 */
SendCourrierAnonymize.prototype.delay = 10;

/**
 * Allowed values for the <code>target</code> property.
 * @enum {String}
 * @readonly
 */
SendCourrierAnonymize.TargetEnum = {
  /**
   * value: "exp"
   * @const
   */
  exp: "exp",

  /**
   * value: "dest"
   * @const
   */
  dest: "dest",

  /**
   * value: "content"
   * @const
   */
  content: "content"
};
/**
 * Délai en nombre de jours (min. 1, max. 400) à compter de l'impression, après lesquels vous souhaitez que l'anonymisation ai lieu.
 * @member {Array.<module:model/SendCourrierAnonymize.TargetEnum>} target
 */
SendCourrierAnonymize.prototype.target = undefined;

