/*
 * Merci facteur API
 * Merci facteur PRO vous permet d'envoyer des courriers depuis votre applicatif via son API.     Types de courriers disponibles :   - Lettre de une ou plusieurs pages.  - Carte postale avec ou sans enveloppe  - Carte pliée  - Carte géante  - Carte non pliée  - Photos sur papier brillant    Modes d'envois disponibles :   - Envoi normal (lettre verte)  - Lettre suivie  - Recommandé avec avis de réception      Au sujet des webhooks : [`https://github.com/MerciFacteur/Merci-facteur-API/blob/master/README.md#webhooks`](https://github.com/MerciFacteur/Merci-facteur-API/blob/master/README.md#webhooks)     Librairie PHP et exemples d'intégration : [`https://github.com/MerciFacteur/Merci-facteur-API`](https://github.com/MerciFacteur/Merci-facteur-API)    Infos générales sur l'API : [`https://github.com/MerciFacteur/Merci-facteur-API/blob/master/README.md`](https://github.com/MerciFacteur/Merci-facteur-API/blob/master/README.md)    Plus d'informations sur [`https://www.merci-facteur.com/pro`](https://www.merci-facteur.com/pro)    N'hésitez pas à nous contacter via [`https://www.merci-facteur.com/pro/contact.php`](https://www.merci-facteur.com/pro/contact.php)
 *
 * OpenAPI spec version: 1.2.7
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.50
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {SourcePublipostageSource} from './SourcePublipostageSource';

/**
 * The SourcePublipostageBody model module.
 * @module model/SourcePublipostageBody
 * @version 1.2.7
 */
export class SourcePublipostageBody {
  /**
   * Constructs a new <code>SourcePublipostageBody</code>.
   * @alias module:model/SourcePublipostageBody
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>SourcePublipostageBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SourcePublipostageBody} obj Optional instance to populate.
   * @return {module:model/SourcePublipostageBody} The populated <code>SourcePublipostageBody</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new SourcePublipostageBody();
      if (data.hasOwnProperty('idUser'))
        obj.idUser = ApiClient.convertToType(data['idUser'], 'Number');
      if (data.hasOwnProperty('templateValidation'))
        obj.templateValidation = ApiClient.convertToType(data['templateValidation'], Object);
      if (data.hasOwnProperty('source'))
        obj.source = SourcePublipostageSource.constructFromObject(data['source']);
    }
    return obj;
  }
}

/**
 * Id de l'utilisateur qui effectue l'envoi.
 * @member {Number} idUser
 */
SourcePublipostageBody.prototype.idUser = undefined;

/**
 * un json avec la valeur templateValidation telle qu'elle vous a été retourné lors de l'envoi du template sur /templatePublipostage.
 * @member {Object} templateValidation
 */
SourcePublipostageBody.prototype.templateValidation = undefined;

/**
 * @member {module:model/SourcePublipostageSource} source
 */
SourcePublipostageBody.prototype.source = undefined;

