/*
 * Merci facteur API
 * Merci facteur PRO vous permet d'envoyer des courriers depuis votre applicatif via son API.     Types de courriers disponibles :   - Lettre de une ou plusieurs pages.  - Carte postale avec ou sans enveloppe  - Carte pliée  - Carte géante  - Carte non pliée  - Photos sur papier brillant    Modes d'envois disponibles :   - Envoi normal (lettre verte)  - Lettre suivie  - Recommandé avec avis de réception      Au sujet des webhooks : [`https://github.com/MerciFacteur/Merci-facteur-API/blob/master/README.md#webhooks`](https://github.com/MerciFacteur/Merci-facteur-API/blob/master/README.md#webhooks)     Librairie PHP et exemples d'intégration : [`https://github.com/MerciFacteur/Merci-facteur-API`](https://github.com/MerciFacteur/Merci-facteur-API)    Infos générales sur l'API : [`https://github.com/MerciFacteur/Merci-facteur-API/blob/master/README.md`](https://github.com/MerciFacteur/Merci-facteur-API/blob/master/README.md)    Plus d'informations sur [`https://www.merci-facteur.com/pro`](https://www.merci-facteur.com/pro)    N'hésitez pas à nous contacter via [`https://www.merci-facteur.com/pro/contact.php`](https://www.merci-facteur.com/pro/contact.php)
 *
 * OpenAPI spec version: 1.2.7
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.50
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The TemplatePublipostageBody model module.
 * @module model/TemplatePublipostageBody
 * @version 1.2.7
 */
export class TemplatePublipostageBody {
  /**
   * Constructs a new <code>TemplatePublipostageBody</code>.
   * @alias module:model/TemplatePublipostageBody
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>TemplatePublipostageBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TemplatePublipostageBody} obj Optional instance to populate.
   * @return {module:model/TemplatePublipostageBody} The populated <code>TemplatePublipostageBody</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new TemplatePublipostageBody();
      if (data.hasOwnProperty('typeTemplate'))
        obj.typeTemplate = ApiClient.convertToType(data['typeTemplate'], 'String');
      if (data.hasOwnProperty('template'))
        obj.template = ApiClient.convertToType(data['template'], 'String');
    }
    return obj;
  }
}

/**
 * Allowed values for the <code>typeTemplate</code> property.
 * @enum {String}
 * @readonly
 */
TemplatePublipostageBody.TypeTemplateEnum = {
  /**
   * value: "file"
   * @const
   */
  file: "file",

  /**
   * value: "base64"
   * @const
   */
  base64: "base64"
};
/**
 * Type de template envoyé (\"file\" pour une URL vers un fichier docx, ou \"base64\" pour un fichier encodé en base64).
 * @member {module:model/TemplatePublipostageBody.TypeTemplateEnum} typeTemplate
 */
TemplatePublipostageBody.prototype.typeTemplate = undefined;

/**
 * URL du fichier docx, ou sa version encodée en base64.
 * @member {String} template
 */
TemplatePublipostageBody.prototype.template = undefined;

