<?php

/**
 * InlineResponse20010Content
 *
 * PHP version 5
 *
 * @category Class
 * @package  MerciFacteurApi\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Merci facteur API
 *
 * Merci facteur PRO vous permet d'envoyer des courriers depuis votre applicatif via son API.     Types de courriers disponibles :   - Lettre de une ou plusieurs pages.  - Carte postale avec ou sans enveloppe  - Carte pliée  - Carte géante  - Carte non pliée  - Photos sur papier brillant    Modes d'envois disponibles :   - Envoi normal (lettre verte)  - Lettre suivie  - Recommandé avec avis de réception      Au sujet des webhooks : [`https://github.com/MerciFacteur/Merci-facteur-API/blob/master/README.md#webhooks`](https://github.com/MerciFacteur/Merci-facteur-API/blob/master/README.md#webhooks)     Librairie PHP et exemples d'intégration : [`https://github.com/MerciFacteur/Merci-facteur-API`](https://github.com/MerciFacteur/Merci-facteur-API)    Infos générales sur l'API : [`https://github.com/MerciFacteur/Merci-facteur-API/blob/master/README.md`](https://github.com/MerciFacteur/Merci-facteur-API/blob/master/README.md)    Plus d'informations sur [`https://www.merci-facteur.com/pro`](https://www.merci-facteur.com/pro)    N'hésitez pas à nous contacter via [`https://www.merci-facteur.com/pro/contact.php`](https://www.merci-facteur.com/pro/contact.php)
 *
 * OpenAPI spec version: 1.2.7
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.51
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace MerciFacteurApi\Client\Model;

use \ArrayAccess;
use \MerciFacteurApi\Client\ObjectSerializer;

/**
 * InlineResponse20010Content Class Doc Comment
 *
 * @category Class
 * @description object avec, pour chaque pays demandé, le montant de l&#x27;affranchissement et la zone géographique
 * @package  MerciFacteurApi\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class InlineResponse20010Content implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $swaggerModelName = 'inline_response_200_10_content';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $swaggerTypes = [
        'photo_ht' => 'string',
        'lettre_ht' => 'string',
        'carte_ht' => 'string',
        'total_content_ht' => 'string'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $swaggerFormats = [
        'photo_ht' => null,
        'lettre_ht' => null,
        'carte_ht' => null,
        'total_content_ht' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'photo_ht' => 'photoHt',
        'lettre_ht' => 'lettreHt',
        'carte_ht' => 'carteHt',
        'total_content_ht' => 'totalContentHt'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'photo_ht' => 'setPhotoHt',
        'lettre_ht' => 'setLettreHt',
        'carte_ht' => 'setCarteHt',
        'total_content_ht' => 'setTotalContentHt'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'photo_ht' => 'getPhotoHt',
        'lettre_ht' => 'getLettreHt',
        'carte_ht' => 'getCarteHt',
        'total_content_ht' => 'getTotalContentHt'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }



    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['photo_ht'] = isset($data['photo_ht']) ? $data['photo_ht'] : null;
        $this->container['lettre_ht'] = isset($data['lettre_ht']) ? $data['lettre_ht'] : null;
        $this->container['carte_ht'] = isset($data['carte_ht']) ? $data['carte_ht'] : null;
        $this->container['total_content_ht'] = isset($data['total_content_ht']) ? $data['total_content_ht'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets photo_ht
     *
     * @return string
     */
    public function getPhotoHt()
    {
        return $this->container['photo_ht'];
    }

    /**
     * Sets photo_ht
     *
     * @param string $photo_ht montant HT des photos
     *
     * @return $this
     */
    public function setPhotoHt($photo_ht)
    {
        $this->container['photo_ht'] = $photo_ht;

        return $this;
    }

    /**
     * Gets lettre_ht
     *
     * @return string
     */
    public function getLettreHt()
    {
        return $this->container['lettre_ht'];
    }

    /**
     * Sets lettre_ht
     *
     * @param string $lettre_ht montant HT des pages de lettres
     *
     * @return $this
     */
    public function setLettreHt($lettre_ht)
    {
        $this->container['lettre_ht'] = $lettre_ht;

        return $this;
    }

    /**
     * Gets carte_ht
     *
     * @return string
     */
    public function getCarteHt()
    {
        return $this->container['carte_ht'];
    }

    /**
     * Sets carte_ht
     *
     * @param string $carte_ht montant HT de la carte
     *
     * @return $this
     */
    public function setCarteHt($carte_ht)
    {
        $this->container['carte_ht'] = $carte_ht;

        return $this;
    }

    /**
     * Gets total_content_ht
     *
     * @return string
     */
    public function getTotalContentHt()
    {
        return $this->container['total_content_ht'];
    }

    /**
     * Sets total_content_ht
     *
     * @param string $total_content_ht montant HT du contenu du courrier
     *
     * @return $this
     */
    public function setTotalContentHt($total_content_ht)
    {
        $this->container['total_content_ht'] = $total_content_ht;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
